const CONFIGUREOPTIONS = 'Config: options-set';
const BASIC = 'ChatBot: chat message to get to know streamer/bot';
const SOCIAL = 'ChatBot: chat message to be repled by social media links';
const SHOUTOUT = 'ChatBot: chat message to link out to other twitch streamer';
const STREAK = 'ChatBot: chat message to return the amount of days in a row the streamer has used bot on stream';
const SOAP = 'ChatBot: chat query to return search result from royality soaps';
const POKEMON = 'Chatbot: chat message to return infomation on a pokemon trading card';
const RESPONSE = '*: ready response to Twitch';
const MODONLYRESPONSE = '*: ready a mod only response to Twitch';

exports.configureoptions = CONFIGUREOPTIONS;
exports.basic = BASIC;
exports.social = SOCIAL;
exports.shoutout = SHOUTOUT;
exports.streak = STREAK;
exports.soap = SOAP;
exports.poke = POKEMON;
exports.response = RESPONSE;
exports.modonlyresponse = MODONLYRESPONSE;
